[package]
name = "projec_p2"
version = "0.1.1"
authors = ["papanumba"]
edition = "2021"
description = "A small CLI projective plane (RP²) grapher"
repository = "https://github.com/papanumba/projec_p2"
license = "GPL-3.0"

[dependencies]
image = "0.23.0"

[profile.release]
lto = true
strip = true
